[project]
authors = ["Brendan Kirkpatrick"]
channels = ["conda-forge"]
description = "Fault-Compare Setup"
name = "FaultFlipper"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.13.1,<4"
cyclopts = ">=3.1.2,<4"
capstone = ">=5.0.3,<6"
plotly = ">=5.24.1,<6"
pyelftools = ">=0.31,<0.32"
bitstring = ">=4.3.0,<5"
colorama = ">=0.4.6,<0.5"
dynaconf = ">=3.2.7,<4"
altair = ">=5.5.0,<6"
streamlit = ">=1.42.0,<2"
pygments = ">=2.19.1,<3"
icontract = ">=2.7.1,<3"
hypothesis = ">=6.129.3,<7"
rich = ">=13.0.0,<14"

[pypi-dependencies]
lief = ">=0.16.0, <0.17"
pyqt5 = ">=5.15.11, <6"
dearpygui = ">=2.0.0, <3"
alive-progress = ">=3.2.0, <4"
angr = ">=9.2.65, <10"
claripy = ">=9.2.65, <10"
deal = ">=4.24.5, <5"
matplotlib = ">=3.10.0"
scikit-learn = ">=1.6.0"

[tasks]
update = { cmd = [
    "git",
    "submodule",
    "update",
    "--recursive",
] }
compare = { cmd = "python src/compare.py" }
